#!/bin/bash

# allow X11 access
xhost +local:docker

# start sql server
# docker run \
#         -d \
#         -e 'ACCEPT_EULA=Y' \
#         -e 'SA_PASSWORD=pear2010' \
#         -p 1433:1433 \
#         -v ${PWD}/data:/var/opt/mssql \
#         --name vscode-working-sql-server \
#         microsoft/mssql-server-linux

# start vscode
docker run -d \
      -d \
      -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
      -v ${PWD}:/developer/project \
      -v ${HOME}/.vscode:/developer/.vscode \
      -v ${HOME}/.config/Code:/developer/.config/Code \
      -v ${HOME}/.ssh:/developer/.ssh \
      -v ${HOME}/.gitconfig:/developer/.gitconfig \
      -e SSH_AUTH_SOCK=/ssh_auth_sock \
      -e DISPLAY=unix${DISPLAY} \
      -p 5000:5000 \
      -p 3000:3000 \
      -p 3001:3001 \
      --device /dev/snd \
      --name vscode-working \
      cmiles74/docker-vscode

docker exec vscode-working /developer/bin/start-vscode
docker exec vscode-working /developer/bin/start-emacs

