#!/bin/bash

# allow X11 access
xhost +local:docker

# start containers
#docker start vscode-working-sql-server
docker start vscode-working
docker exec vscode-working /developer/bin/start-vscode
docker exec vscode-working /developer/bin/start-emacs
